name: 'Web Pre-Processor'
description: 'Provides tools for processin style and js minifying using styl and uglify'
inputs:
  action:
    description: 'uglifyjs or styl or combine'
    default: 'uglifyjs'
  filename:
    description: 'input file {string} or files {array<string>}'
  output: 
    description: 'Output file'
  regexes:
    description: 'Array used for replace function'
  replaces:
    description: 'Array of replacement strings on matches'

runs:
  using: 'node16'
  main: 'index.js'